name: javacpp
on: [push, pull_request, workflow_dispatch]
env:
  CI_DEPLOY_MODULE: .
  CI_DEPLOY_OPTIONS: -Dmaven.javadoc.skip -Dmaven.test.skip -Dinvoker.skip
  CI_DEPLOY_PLATFORM: ${{ github.job }}
  CI_DEPLOY_SETTINGS: ${{ secrets.CI_DEPLOY_SETTINGS }}
  CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
  CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  STAGING_REPOSITORY: ${{ secrets.STAGING_REPOSITORY }}
jobs:
#  android-arm:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  android-arm64:
    runs-on: ubuntu-20.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
#  android-x86:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  android-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  ios-arm64:
    runs-on: macos-11
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  ios-x86_64:
    runs-on: macos-11
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
#  linux-armhf:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-arm64:
    runs-on: ubuntu-20.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-ppc64le:
    runs-on: ubuntu-20.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
#  linux-x86:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  linux-x86_64:
    runs-on: ubuntu-20.04
    env:
      CI_DEPLOY_OPTIONS: "" # to not skip tests
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-ubuntu@actions
  macosx-arm64:
    runs-on: macos-11
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
  macosx-x86_64:
    runs-on: macos-11
    env:
      CI_DEPLOY_OPTIONS: "" # to not skip tests
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
#  windows-x86:
#    runs-on: windows-2019
#    steps:
#      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  windows-x86_64:
    runs-on: windows-2019
    env:
      CI_DEPLOY_OPTIONS: "" # to not skip tests
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
  redeploy:
#    needs: [android-arm, android-arm64, android-x86, android-x86_64, ios-arm64, ios-x86_64, linux-armhf, linux-arm64, linux-ppc64le, linux-x86, linux-x86_64, macosx-arm64, macosx-x86_64, windows-x86, windows-x86_64]
    needs: [android-arm64, android-x86_64, ios-arm64, ios-x86_64, linux-arm64, linux-ppc64le, linux-x86_64, macosx-arm64, macosx-x86_64, windows-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/redeploy@actions
